openapi: 3.0.1
info:
  title: Swagger Floria Capital
  description: This is Floria Server api document
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://api.floriacapital.dev
paths:
  /private/loan-formula-information/get-loan-type-information-by-type:
    get:
      tags:
      - Private
      summary: API call from back-end to get loan formula information by type
  /private/loan-formula-information/get-loan-formula-by-type-and-loan-amount-middle:
    get:
      tags:
        - Private
      summary: API call from back-end to get loan formula by type and loan amount between min and max
  /private/loan-formula-information/get-loan-term:
    get:
      tags:
        - Private
      summary: Get loan term from loan formula information
  /new-loan-application/get-loan-type-information:
    get:
      tags:
        - Private
      summary: API call from front-end to get loan formula information
  /new-loan-application/get-loan-calculator-sample-result:
    get:
      tags:
      - Loan
      summary: get loan calculator sample result
      operationId: loanSample
  /customer-service/create-ticket:
    post:
      tags:
      - Customer Service
      description: Auto generated using Swagger Inspector
  /client/user-access-service/check-user-can-apply-loan:
    get:
      tags:
      - Loan
      summary: check if user is eligible to apply loan
      description: Auto generated using Swagger Inspector
      security:
      - floria_auth:
        - write:loan 
  
  /user-access-service/create-loan-draft:
      post:
        tags:
        - Loan
        description: Create loan draft
                
  /client/user-access-service/load-loan-draft:
    get:
      tags:
      - Loan
      description: Load loan draft
      security:
      - floria_auth:
        - read:loan     
  /client/user-access-service/create-loan-history:
      post:
        tags:
        - Loan              
        description: Create loan history
  /client/user-access-service/load-list-loan-history:
    get:
      tags:
      - Loan                
      description: Load list loan history
      security:
      - floria_auth:
        - read:loan
  /client/user-access-service/cancel-loan-history:
    patch:
      tags:
      - Loan                
      description: Cancel Loan History
      security:
      - floria_auth:
        - write:loan         
  
  /client/user-access-service/get-payment-schedule:
    post:
      tags:
      - Loan                
      description: Get list payment schedule loan
      security:
      - floria_auth:
        - write:loan    
  /client/user-access-service/export-payment-loan:
    post:
      tags:
      - Loan                
      description: Get list payment schedule loan simulator
      security:
      - floria_auth:
        - write:loan                        
  /client/user-access-service/get-questionnaire:
    post:
      tags:
      - Questionnaire
      summary: User gets specific questions and responds to questionnaire
      description: Retrieve questionnaire
      security:
      - floria_auth:
        - read:loan   
  /client/user-access-service/create-presigner-url-upload-avatar:
    post:
      tags:
      - Profile                
      description: Create presigner url upload file
      security:
      - floria_auth:
        - write:profile      
  /client/user-access-service/delete-and-update-avatar-for-user:
    post:
      tags:
      - Profile                
      description:  Delete file from s3 - Update avatar for user profile - Update avatar for cognito user
      security:
      - floria_auth:
        - write:profile      
  /user-access-service/save-and-send-verify-code-for-user:
    post:
      tags:
      - Verification                
      description:  Temporarily save data, generate verify code and send verify code for user
      
  /user-access-service/save-and-verify-phone-number-for-current-user:
    post:
      tags:
      - Verification                
      summary:  Verify phone number for user
      
  /user-access-service/save-and-verify-email-for-current-user:
    post:
      tags:
      - Verification                
      summary:  Verify email for user
      
  /user-access-service/save-and-resend-verify-code-for-user:
    post:
      tags:
      - Verification                
      summary:  Resend verify code for user
      
  /plaid/get-link-token:
    get:
      tags:
      - Plaid
      summary: Create Plaid link token
      operationId: plaidLinkToken
      security:
      - floria_auth:
        - read:link
  /plaid/create-bank-account-token:
    post:
      tags:
      - Plaid
      summary: Plaid generate and save bank account token
      operationId: bankAccountToken
      security:
      - floria_auth:
        - read:link
  /admin/user-access-service/get-list-loan:
    get:
      tags:
        - Admin
      summary: Get current loan list
      security:
      - floria_auth:
        - write:token
  /admin/update-loan-type-information:
    put:
      tags:
      - Admin                
      description:  Update loan type information
      security:
      - floria_auth:
        - write:loan   
  /admin/update-loan-formula-information:
    put:
      tags:
      - Admin                
      description:  Update loan formula information
      security:
      - floria_auth:
        - write:loan  
  /admin/create-loan-formula-information:
    post:
      tags:
      - Admin                
      summary:  Create loan formula information
      security:
      - floria_auth:
        - write:loan         
  /admin/disable-loan-formula-information:
    put:
      tags:
      - Admin                
      summary:  Disable loan formula information
      security:
      - floria_auth:
        - write:loan  
  /admin/get-loan-formulas-information-by-type:
    get:
      tags:
      - Admin                
      summary:  Get loan formulas by type
      security:
      - floria_auth:
        - write:loan  
  /user-access-service/get-question-property-information:
    get:
      tags:
      - Questionnaire                
      summary:  Get question property information
  /admin/user-access-service/documents/view/get-list-customer:
    get:
      tags:
      - Documents             
      summary: Admin Dashboard - Documents Uploaded - Get List Customer
      security:
      - floria_auth:
        - read:profile  
  /admin/user-access-service/documents/view//admin/user-access-service/documents/view/get-list-loans-from-user-profile-id:
    get:
      tags:
      - Documents                 
      summary: Admin Dashboard - Documents Uploaded - Get List List Loans
      security:
      - floria_auth:
        - read:loan  
  /admin/user-access-service/documents/view/get-list-document-type:
    get:
      tags:
      - Documents             
      summary: Admin Dashboard - Documents Uploaded - Get List Customer
      security:
      - floria_auth:
        - read:document  
  /admin/user-access-service/documents/view/get-list-document-template:
    get:
      tags:
      - Documents                 
      summary: Admin Dashboard - Documents Uploaded - Get List document template
      security:
      - floria_auth:
        - read:document  
  /admin/user-access-service/documents/update/get-presigner-url-upload:
    get:
      tags:
      - Documents             
      summary: Admin Dashboard - Documents Uploaded - Get presigner url to allow upload file to S3
      security:
      - floria_auth:
        - read:s3  
  /admin/user-access-service/documents/view/get-list-loan-document-uploaded-from-loan-history-id:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - Documents Uploaded - Get list loan document uploaded
      security:
      - floria_auth:
        - read:loan
  /admin/user-access-service/new-loan/view/get-list-loan-pending:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get list loan Pending
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-list-loan-pre-approved:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get list loan Pre-Approved
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-reason-list-in-popup-incomplete-form:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get reason list in popup incomplete form
      security:
      - floria_auth:
        - read:loan  
  /admin/user-access-service/new-loan/view/get-reason-list-in-popup-reject-form:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get reason list in popup reject form
      security:
      - floria_auth:
        - read:loan  
  /admin/user-access-service/new-loan/view/get-profile-header:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Header get profile data
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-underwriting-summary:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get data Underwriting Summary
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-loan-collateral-information-by-loan-history-id:
    get:
      tags:
      - Admin                
      summary:  Admin Dashboard - New Loan - Get data Loan Collateral Information
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-history-reject:
    patch:
      tags:
      - Admin                
      summary: Admin Dashboard - New Loan - Reject loan
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-history-incomplete:
    patch:
      tags:
      - Admin                
      summary: Admin Dashboard - New Loan - Set loan incomplete
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-history-pending-for-1st-check:
    patch:
      tags:
      - Admin                
      summary: Admin Dashboard - New Loan - Set loan pending for 1st check
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-history-approve:
    patch:
      tags:
      - Admin                
      summary: Admin Dashboard - New Loan - Approve loan - 1st and 2nd
      security:
      - floria_auth:
        - read:loan 
  /admin/user-access-service/new-loan/update/verify-collateral-information:
    patch:
      tags:
      - Admin                
      summary: Admin Dashboard - New Loan - Verify collateral information
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-collateral-information:
    put:
      tags:
      - Admin                
      summary: Save loan collateral information
      security:
      - floria_auth:
        - write:loan   
  /admin/user-access-service/new-loan/update/save-and-update-note-for-loan-collateral-information:
    put:
      tags:
      - Admin                
      summary: Save and update note for loan collateral information
      security:
      - floria_auth:
        - write:loan   
  /admin/user-access-service/new-loan/update/save-loan-insurance-information:
    put:
      tags:
      - Admin                
      summary: Save loan insurance information
      security:
      - floria_auth:
        - write:loan   
  /admin/user-access-service/new-loan/view/get-loan-insurance-information-by-loan-history-id:
    get:
      tags:
      - Admin                
      summary: get loan insurance information by loan history id
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-loan-detail-fee-setting-by-loan-history-id:
    get:
      tags:
      - Admin                
      summary: get detail fee settings by loan history id
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/update/save-loan-detail-fee-setting-by-loan-history-id:
    put:
      tags:
      - Admin                
      summary: save loan detail fee setting by loan history id
      security:
      - floria_auth:
        - read:loan   
  /admin/user-access-service/new-loan/view/get-loan-folders-by-loan-history-id:
    get:
      tags:
      - Admin                
      summary: get loan folders by loan history id
      security:
      - floria_auth:
        - read:loan
  /admin/user-access-service/new-loan/view/get-loan-notes-by-loan-folder-id:
    get:
      tags:
      - Admin                
      summary: get loan notes by loan folder id
      security:
      - floria_auth:
        - read:loan     
  /admin/user-access-service/new-loan/create/save-loan-note-general:
    post:
      tags:
      - Admin                
      summary: save loan note of general type
      security:
      - floria_auth:
        - read:loan  
  /admin/user-access-service/new-loan/create/save-loan-note-for-loan-folder:
    post:
      tags:
      - Admin                
      summary: save loan note for loan folder
      security:
      - floria_auth:
        - read:loan    
components:
  securitySchemes:
    floria_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.floriacapital.dev
          scopes:
            write:loans: modify loans in your account
            read:loans: read your loans information
            read:link: get Plaid link token
            write:token: generate a bank account token
            write:profile : modify profile
            read:profile : read 
            read:document : read documents
            read:s3 : access to s3 urls
    api_key:
      type: apiKey
      name: api_key
      in: header


     

    